apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
      - image: shifterbit/captsone-django:latest
        imagePullPolicy: Always
        name: dealership
        env:
          - name: NLU_API_KEY
            valueFrom:
               secretKeyRef:
                  name: nlusecret
                  key: apikey
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always
  replicas: 1
